//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class puesto_trabajo
    {
        public int id { get; set; }
        public string nombre_Compania { get; set; }
        public string tipo { get; set; }
        public byte[] logo { get; set; }
        public string URL { get; set; }
        public string Posicion { get; set; }
        public string Ubicación { get; set; }
        public int Categoría { get; set; }
        public string Descripcion_trabajo { get; set; }
        public string Como_aplicar { get; set; }
        public string Email { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
